const CAMPUS_ADDRESS = '广东省肇庆市鼎湖区莲花镇丰乐路20号';

function campusAddress(placeName) {
  return CAMPUS_ADDRESS + ' 广州应用科技学院肇庆校区' + placeName;
}

module.exports = [
  {
    id: 1,
    name: "广州应用科技学院(肇庆校区)图书馆",
    type: "学习场所",
    description: "OSM 标注的校区图书馆建筑，适合作为自习、借阅和学习资源检索的导航点。",
    openTime: "08:00-22:00",
    latitude: 23.2720399,
    longitude: 112.6800859,
    mapX: 53,
    mapY: 25,
    image: "",
    featured: true,
    tagline: "真实坐标图书馆，自习和资料检索首选点",
    bestFor: "学生熟悉图书借阅、自习座位和电子资源入口",
    bestTime: "工作日早上或晚间自习时段",
    nearby: [
      "格致楼",
      "博雅楼",
      "综合体育馆"
    ],
    nextStops: [
      2,
      3
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区图书馆",
    tips: "该点位来自 OpenStreetMap 建筑中心点，已转换为微信地图使用的 GCJ-02 坐标。",
    source: "OpenStreetMap",
    osmId: "way/1395664566",
    wgs84Latitude: 23.2747618,
    wgs84Longitude: 112.674994,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 2,
    name: "格致楼",
    type: "教学楼",
    description: "OSM 标注的 college building，是肇庆校区教学楼点位之一，可作为课程导航目的地。",
    openTime: "07:30-22:00",
    latitude: 23.2701416,
    longitude: 112.6806125,
    mapX: 54,
    mapY: 40,
    image: "",
    featured: true,
    tagline: "真实坐标教学楼，适合课程和教学区导航",
    bestFor: "第一次按课表寻找教学楼的学生",
    bestTime: "上课前 15 分钟",
    nearby: [
      "博雅楼",
      "行政中心",
      "明德楼"
    ],
    nextStops: [
      4,
      6
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区格致楼",
    tips: "导航前请结合课表确认教室所在楼栋和楼层。",
    source: "OpenStreetMap",
    osmId: "way/1395664512",
    wgs84Latitude: 23.272863,
    wgs84Longitude: 112.6755196,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 3,
    name: "一期桃园饭堂",
    type: "生活场所",
    description: "OSM 标注的校内 food court 建筑，是靠近一期生活区的餐饮点。",
    openTime: "07:00-20:00",
    latitude: 23.2733271,
    longitude: 112.6817212,
    mapX: 62,
    mapY: 18,
    image: "",
    featured: true,
    tagline: "一期生活区餐饮点，适合报到后快速补给",
    bestFor: "报到、下课、晚自习前后的用餐补给",
    bestTime: "早餐后或午间错峰前往",
    nearby: [
      "校医务室",
      "瑞幸咖啡",
      "图书馆"
    ],
    nextStops: [
      1,
      15
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区一期桃园饭堂",
    tips: "午餐高峰建议错峰；该坐标来自 OSM 建筑中心点，已转换为 GCJ-02。",
    source: "OpenStreetMap",
    osmId: "way/1395664574",
    wgs84Latitude: 23.276049,
    wgs84Longitude: 112.6766294,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 4,
    name: "明德楼",
    type: "教学楼",
    description: "OSM 标注的 college building，是校区东北侧教学楼点位。",
    openTime: "07:30-22:00",
    latitude: 23.2709998,
    longitude: 112.6822083,
    mapX: 66,
    mapY: 34,
    image: "/images/campus/mingde-building-wide.jpg",
    featured: true,
    tagline: "教学楼真实定位，适合从图书馆和行政中心顺路前往",
    bestFor: "需要定位东北侧教学楼的同学",
    bestTime: "上课前、考试前踩点",
    nearby: [
      "格致楼",
      "行政中心",
      "图书馆"
    ],
    nextStops: [
      2,
      6
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区明德楼",
    tips: "大型考试或跨楼上课时建议提前查看步行时间。",
    source: "OpenStreetMap",
    osmId: "way/1395664526",
    wgs84Latitude: 23.2737218,
    wgs84Longitude: 112.677116,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 5,
    name: "集贤苑A栋",
    type: "宿舍楼",
    description: "OSM 标注的 dormitory building，可用于宿舍区真实定位导航。",
    openTime: "全天",
    latitude: 23.2701201,
    longitude: 112.677304,
    mapX: 38,
    mapY: 45,
    image: "",
    featured: false,
    tagline: "真实宿舍楼坐标，适合报到和返寝导航",
    bestFor: "住宿、搬运行李、熟悉生活区的学生",
    bestTime: "报到日、返校日和晚间返寝",
    nearby: [
      "集贤苑B栋",
      "集贤苑C栋",
      "学思苑G栋"
    ],
    nextStops: [
      15,
      16
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区集贤苑A栋",
    tips: "宿舍楼门禁和实际入口请以现场管理为准。",
    source: "OpenStreetMap",
    osmId: "way/1395664575",
    wgs84Latitude: 23.2728412,
    wgs84Longitude: 112.6722121,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 6,
    name: "行政中心",
    type: "办事服务",
    description: "OSM 标注的行政中心建筑，适合办理咨询、证明、校园事务指引等。",
    openTime: "08:30-17:30",
    latitude: 23.2698269,
    longitude: 112.6814309,
    mapX: 60,
    mapY: 42,
    image: "/images/campus/admin-center.jpg",
    featured: true,
    tagline: "真实坐标行政中心，办事咨询优先定位点",
    bestFor: "需要办理证明、咨询学籍或校园事务的同学",
    bestTime: "工作日上午，排队压力较小",
    nearby: [
      "格致楼",
      "博雅楼",
      "明德楼"
    ],
    nextStops: [
      2,
      4
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区行政中心",
    tips: "带好证件和材料能减少重复往返。",
    source: "OpenStreetMap",
    osmId: "way/1395664513",
    wgs84Latitude: 23.2725484,
    wgs84Longitude: 112.676338,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 7,
    name: "博雅楼",
    type: "教学楼",
    description: "OSM 标注的 college building，是格致楼附近的教学楼点位。",
    openTime: "07:30-22:00",
    latitude: 23.2693502,
    longitude: 112.6799501,
    mapX: 50,
    mapY: 48,
    image: "",
    featured: true,
    tagline: "格致楼附近教学楼，适合按课表快速定位",
    bestFor: "公共课程、教学活动和课前踩点",
    bestTime: "上课前 15 分钟",
    nearby: [
      "格致楼",
      "行政中心",
      "图书馆"
    ],
    nextStops: [
      2,
      1
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区博雅楼",
    tips: "如果同一节课跨楼，建议先确认博雅楼与格致楼之间的步行时间。",
    source: "OpenStreetMap",
    osmId: "way/1395664514",
    wgs84Latitude: 23.2720715,
    wgs84Longitude: 112.6748572,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 8,
    name: "菜鸟驿站",
    type: "生活场所",
    description: "OSM 标注的菜鸟驿站节点，适合快递取件和生活服务定位。",
    openTime: "09:00-20:30",
    latitude: 23.2675236,
    longitude: 112.6717816,
    mapX: 16,
    mapY: 70,
    image: "",
    featured: false,
    tagline: "真实快递点坐标，适合取件和学生生活补给",
    bestFor: "处理日常快递、报到物品和生活包裹",
    bestTime: "下午非高峰时段",
    nearby: [
      "J4治平楼",
      "二期桃蹊饭堂",
      "库迪咖啡"
    ],
    nextStops: [
      12,
      14
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区菜鸟驿站",
    tips: "傍晚取件人流较多，建议错峰前往。",
    source: "OpenStreetMap",
    osmId: "node/12918810980",
    wgs84Latitude: 23.2702428,
    wgs84Longitude: 112.6666985,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 9,
    name: "J3修齐楼",
    type: "教学楼",
    description: "OSM 标注的 college building，是二期片区教学楼点位之一。",
    openTime: "07:30-22:00",
    latitude: 23.2673008,
    longitude: 112.6738403,
    mapX: 28,
    mapY: 65,
    image: "",
    featured: true,
    tagline: "二期片区教学楼真实定位",
    bestFor: "在二期片区上课或考试的学生",
    bestTime: "上课前、考试前踩点",
    nearby: [
      "J4治平楼",
      "S5致用楼",
      "二期桃蹊饭堂"
    ],
    nextStops: [
      10,
      11
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区J3修齐楼",
    tips: "二期片区楼栋较集中，建议按楼名而不是模糊地点导航。",
    source: "OpenStreetMap",
    osmId: "way/1395664564",
    wgs84Latitude: 23.2700217,
    wgs84Longitude: 112.6687568,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 10,
    name: "J4治平楼",
    type: "教学楼",
    description: "OSM 标注的 college building，是二期片区教学楼点位之一。",
    openTime: "07:30-22:00",
    latitude: 23.2666123,
    longitude: 112.6728912,
    mapX: 23,
    mapY: 73,
    image: "",
    featured: true,
    tagline: "二期片区教学楼真实定位",
    bestFor: "二期片区课程、实训或考试导航",
    bestTime: "上课前、考试前踩点",
    nearby: [
      "J3修齐楼",
      "二期桃蹊饭堂",
      "菜鸟驿站"
    ],
    nextStops: [
      9,
      14
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区J4治平楼",
    tips: "报到初期容易和 J3 修齐楼混淆，建议收藏该点位。",
    source: "OpenStreetMap",
    osmId: "way/1395664563",
    wgs84Latitude: 23.2693335,
    wgs84Longitude: 112.6678079,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 11,
    name: "S5致用楼",
    type: "教学楼",
    description: "OSM 标注的 college building，位于校区二期与宿舍片区之间。",
    openTime: "07:30-22:00",
    latitude: 23.2682534,
    longitude: 112.6755107,
    mapX: 35,
    mapY: 60,
    image: "/images/campus/basketball-gym.jpg",
    featured: true,
    tagline: "S5 教学楼真实坐标，适合课程导航",
    bestFor: "按课表查找 S5 楼教室的学生",
    bestTime: "上课前 15 分钟",
    nearby: [
      "J3修齐楼",
      "学思苑G栋",
      "集贤苑C栋"
    ],
    nextStops: [
      9,
      16
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区S5致用楼",
    tips: "S5 与宿舍片区距离较近，晚课后返寝可顺路规划。",
    source: "OpenStreetMap",
    osmId: "way/1395664565",
    wgs84Latitude: 23.2709745,
    wgs84Longitude: 112.6704201,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 12,
    name: "二期桃蹊饭堂",
    type: "生活场所",
    description: "OSM 标注的 food court 节点，是二期片区餐饮点。",
    openTime: "07:00-20:00",
    latitude: 23.2662932,
    longitude: 112.6714693,
    mapX: 18,
    mapY: 77,
    image: "",
    featured: false,
    tagline: "二期片区餐饮点，适合 J3/J4 附近用餐",
    bestFor: "二期上课、实训、晚归用餐的同学",
    bestTime: "午餐和晚餐错峰时段",
    nearby: [
      "J4治平楼",
      "J3修齐楼",
      "菜鸟驿站"
    ],
    nextStops: [
      10,
      9
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区二期桃蹊饭堂",
    tips: "该点位来自 OSM 节点，适合导航到饭堂附近。",
    source: "OpenStreetMap",
    osmId: "node/12918811010",
    wgs84Latitude: 23.269035,
    wgs84Longitude: 112.6663983,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 13,
    name: "校医务室",
    type: "应急服务",
    description: "OSM 标注为诊所/医务室的校内医疗点，可用于身体不适和应急支持导航。",
    openTime: "08:30-21:00",
    latitude: 23.2738525,
    longitude: 112.681098,
    mapX: 59,
    mapY: 15,
    image: "",
    featured: true,
    tagline: "真实医务室坐标，身体不适时优先确认",
    bestFor: "身体不适、轻微受伤、需要就医指引的同学",
    bestTime: "不适时立即前往或先联系辅导员确认",
    nearby: [
      "一期桃园饭堂",
      "瑞幸咖啡",
      "图书馆"
    ],
    nextStops: [
      3,
      1
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区诊所(医务室)",
    tips: "紧急情况应优先拨打急救电话，并同步联系辅导员或宿管。",
    source: "OpenStreetMap",
    osmId: "node/12918811011",
    wgs84Latitude: 23.2765751,
    wgs84Longitude: 112.6760013,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 14,
    name: "广州应用科技学院公交站",
    type: "交通入口",
    description: "OSM 标注的肇庆公交站点，可用于返校、离校和周边出行定位。",
    openTime: "以实际班次为准",
    latitude: 23.2693744,
    longitude: 112.6830957,
    mapX: 72,
    mapY: 48,
    image: "",
    featured: true,
    tagline: "肇庆公交站真实坐标，返校离校路线起点",
    bestFor: "周末出行、返校、第一次找公交方向的学生",
    bestTime: "出行前 15 分钟到达",
    nearby: [
      "行政中心",
      "格致楼",
      "明德楼"
    ],
    nextStops: [
      6,
      2
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区广州应用科技学院公交站",
    tips: "公交班次可能随时间调整，出行前建议结合地图 App 和学校通知确认。",
    source: "OpenStreetMap",
    osmId: "node/10072993083",
    wgs84Latitude: 23.2720968,
    wgs84Longitude: 112.6780001,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 15,
    name: "集贤苑B栋",
    type: "宿舍楼",
    description: "OSM 标注的 dormitory building，可用于宿舍楼真实导航。",
    openTime: "全天",
    latitude: 23.2697328,
    longitude: 112.6767644,
    mapX: 34,
    mapY: 50,
    image: "",
    featured: false,
    tagline: "集贤苑宿舍楼真实坐标",
    bestFor: "住宿、搬运行李、晚间返寝",
    bestTime: "报到日、返校日和晚间返寝",
    nearby: [
      "集贤苑A栋",
      "集贤苑C栋",
      "学思苑G栋"
    ],
    nextStops: [
      5,
      16
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区集贤苑B栋",
    tips: "宿舍楼实际入口和门禁以现场管理为准。",
    source: "OpenStreetMap",
    osmId: "way/1395664576",
    wgs84Latitude: 23.2724538,
    wgs84Longitude: 112.671672,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 16,
    name: "集贤苑C栋",
    type: "宿舍楼",
    description: "OSM 标注的 dormitory building，可用于宿舍楼真实导航。",
    openTime: "全天",
    latitude: 23.2693335,
    longitude: 112.6760697,
    mapX: 30,
    mapY: 54,
    image: "",
    featured: false,
    tagline: "集贤苑宿舍楼真实坐标",
    bestFor: "住宿、搬运行李、熟悉宿舍区",
    bestTime: "报到日、返校日和晚间返寝",
    nearby: [
      "集贤苑A栋",
      "集贤苑B栋",
      "学思苑G栋"
    ],
    nextStops: [
      15,
      17
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区集贤苑C栋",
    tips: "第一次返寝建议从公交站或教学楼规划步行路线。",
    source: "OpenStreetMap",
    osmId: "way/1395664577",
    wgs84Latitude: 23.2720548,
    wgs84Longitude: 112.6709768,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 17,
    name: "学思苑G栋",
    type: "宿舍楼",
    description: "OSM 标注的 dormitory building，位于 S5 致用楼附近。",
    openTime: "全天",
    latitude: 23.2689911,
    longitude: 112.6753394,
    mapX: 27,
    mapY: 58,
    image: "",
    featured: false,
    tagline: "学思苑宿舍楼真实坐标",
    bestFor: "住宿、返寝、熟悉宿舍与教学楼动线",
    bestTime: "报到日、返校日和晚间返寝",
    nearby: [
      "S5致用楼",
      "集贤苑C栋",
      "J3修齐楼"
    ],
    nextStops: [
      11,
      16
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区学思苑G栋",
    tips: "晚课后从 S5 返回宿舍可优先查看该点位。",
    source: "OpenStreetMap",
    osmId: "way/1395664578",
    wgs84Latitude: 23.2717127,
    wgs84Longitude: 112.6702461,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 18,
    name: "综合体育馆",
    type: "运动场所",
    description: "OSM 标注的 sports hall 建筑，是校内体育活动和大型活动场地。",
    openTime: "以场馆安排为准",
    latitude: 23.271214,
    longitude: 112.6782484,
    mapX: 43,
    mapY: 32,
    image: "/images/campus/sports-complex.jpg",
    featured: false,
    tagline: "体育活动和大型活动的真实导航点",
    bestFor: "体育课、社团活动、讲座或大型集合",
    bestTime: "按活动时间提前到达",
    nearby: [
      "图书馆",
      "集贤苑A栋",
      "格致楼"
    ],
    nextStops: [
      1,
      5
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区综合体育馆",
    tips: "大型活动期间请以现场入口指引为准。",
    source: "OpenStreetMap",
    osmId: "way/1395664532",
    wgs84Latitude: 23.2739351,
    wgs84Longitude: 112.6731592,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 19,
    name: "瑞幸咖啡",
    type: "生活场所",
    description: "OSM 标注的瑞幸咖啡节点，位于一期片区生活服务范围。",
    openTime: "以门店实际营业为准",
    latitude: 23.2731949,
    longitude: 112.6816013,
    mapX: 63,
    mapY: 20,
    image: "",
    featured: false,
    tagline: "一期片区咖啡补给点",
    bestFor: "自习前后、课间补给、等人集合",
    bestTime: "上午课前或下午自习前",
    nearby: [
      "一期桃园饭堂",
      "校医务室",
      "图书馆"
    ],
    nextStops: [
      3,
      13
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区瑞幸咖啡",
    tips: "营业时间和优惠活动以门店实际信息为准。",
    source: "OpenStreetMap",
    osmId: "node/12918811016",
    wgs84Latitude: 23.2759177,
    wgs84Longitude: 112.6765075,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 20,
    name: "库迪咖啡",
    type: "生活场所",
    description: "OSM 标注的库迪咖啡节点，位于二期饭堂附近。",
    openTime: "以门店实际营业为准",
    latitude: 23.2664132,
    longitude: 112.6709418,
    mapX: 14,
    mapY: 78,
    image: "",
    featured: false,
    tagline: "二期片区咖啡补给点",
    bestFor: "二期上课、自习或等人集合",
    bestTime: "上午课前或下午自习前",
    nearby: [
      "二期桃蹊饭堂",
      "J4治平楼",
      "菜鸟驿站"
    ],
    nextStops: [
      12,
      10
    ],
    address: "广东省肇庆市鼎湖区莲花镇丰乐路20号 广州应用科技学院肇庆校区库迪咖啡",
    tips: "营业时间以门店实际信息为准。",
    source: "OpenStreetMap",
    osmId: "node/12918811047",
    wgs84Latitude: 23.2691541,
    wgs84Longitude: 112.6658709,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 21,
    name: "校门",
    type: "交通入口",
    description: "根据学校手绘地图估算的主校门位置，适合作为到校、报到和校园导航起点。",
    openTime: "全天",
    latitude: 23.2644696,
    longitude: 112.6802652,
    mapX: 62,
    mapY: 85,
    image: "",
    featured: false,
    tagline: "手绘地图估算的主入口点位",
    bestFor: "到校报到、访客入校、校内导航起点",
    bestTime: "到校前或出校前",
    nearby: [
      "行政中心",
      "公交站",
      "风雨连廊"
    ],
    nextStops: [
      6,
      14
    ],
    address: campusAddress("校门"),
    tips: "该坐标由手绘地图位置线性估算，实际入口位置请以现场为准。",
    source: "手绘地图线性估算",
    coordinateStatus: "estimated",
    estimateAverageErrorMeters: 60,
    estimateMaxErrorMeters: 101,
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 22,
    name: "西大门",
    type: "交通入口",
    description: "根据学校手绘地图估算的西侧入口位置，适合西区教学楼和生活区出入导航。",
    openTime: "以现场开放为准",
    latitude: 23.2697405,
    longitude: 112.6714041,
    mapX: 10,
    mapY: 52,
    image: "",
    featured: false,
    tagline: "西区入口估算点位",
    bestFor: "前往西区教学楼、二期饭堂和宿舍区",
    bestTime: "进出西区时",
    nearby: [
      "J4治平楼",
      "J3修齐楼",
      "菜鸟驿站"
    ],
    nextStops: [
      10,
      9
    ],
    address: campusAddress("西大门"),
    tips: "该坐标由手绘地图位置线性估算，需现场或地图选点复核。",
    source: "手绘地图线性估算",
    coordinateStatus: "estimated",
    estimateAverageErrorMeters: 60,
    estimateMaxErrorMeters: 101,
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 23,
    name: "S4笃行楼",
    type: "教学楼",
    description: "手绘地图标注的 S4 教学楼点位，位于中西教学区。",
    openTime: "07:30-22:00",
    latitude: 23.2708907,
    longitude: 112.6770398,
    mapX: 38,
    mapY: 39,
    image: "/images/campus/mingde-building-flower.jpg",
    featured: false,
    tagline: "中西教学区教学楼估算点位",
    bestFor: "按课表寻找 S4 教学楼和周边教室",
    bestTime: "上课前 15 分钟",
    nearby: [
      "S5致用楼",
      "综合体育馆",
      "图书馆"
    ],
    nextStops: [
      11,
      18
    ],
    address: campusAddress("S4笃行楼"),
    tips: "该坐标由手绘地图位置线性估算，楼栋入口需现场复核。",
    source: "手绘地图线性估算",
    coordinateStatus: "estimated",
    estimateAverageErrorMeters: 60,
    estimateMaxErrorMeters: 101,
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 24,
    name: "J1至善楼",
    type: "教学楼",
    description: "手绘地图标注的 J1 教学楼点位，位于东南教学区。",
    openTime: "07:30-22:00",
    latitude: 23.2676106,
    longitude: 112.6832544,
    mapX: 74,
    mapY: 59,
    image: "/images/campus/mingde-building-wide.jpg",
    featured: false,
    tagline: "东南教学区教学楼估算点位",
    bestFor: "寻找 J1 至善楼课程和活动地点",
    bestTime: "上课前、考试前踩点",
    nearby: [
      "J2明德楼",
      "行政中心",
      "公交站"
    ],
    nextStops: [
      4,
      6
    ],
    address: campusAddress("J1至善楼"),
    tips: "该坐标由手绘地图位置线性估算，建议结合现场楼牌确认。",
    source: "手绘地图线性估算",
    coordinateStatus: "estimated",
    estimateAverageErrorMeters: 60,
    estimateMaxErrorMeters: 101,
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 25,
    name: "田径场",
    type: "运动场所",
    description: "根据手绘地图估算的田径场位置，适合体育课、运动会和跑步导航。",
    openTime: "以现场开放为准",
    latitude: 23.27118,
    longitude: 112.679411,
    mapX: 50,
    mapY: 35,
    image: "/images/campus/stadium-aerial.jpg",
    featured: false,
    tagline: "校园运动区估算点位",
    bestFor: "体育课、跑步、运动会集合",
    bestTime: "清晨、傍晚或体育课前",
    nearby: [
      "综合体育馆",
      "篮球场",
      "图书馆"
    ],
    nextStops: [
      18,
      26
    ],
    address: campusAddress("田径场"),
    tips: "该坐标由手绘地图位置线性估算，场地入口以现场为准。",
    source: "手绘地图线性估算",
    coordinateStatus: "estimated",
    estimateAverageErrorMeters: 60,
    estimateMaxErrorMeters: 101,
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 26,
    name: "篮球场",
    type: "运动场所",
    description: "根据手绘地图估算的篮球场位置，适合运动、社团活动和集合导航。",
    openTime: "以现场开放为准",
    latitude: 23.2715074,
    longitude: 112.6814058,
    mapX: 60,
    mapY: 31,
    image: "/images/campus/basketball-gym.jpg",
    featured: false,
    tagline: "校园篮球场估算点位",
    bestFor: "篮球运动、体育活动、临时集合",
    bestTime: "课余和傍晚时段",
    nearby: [
      "田径场",
      "综合体育馆",
      "图书馆"
    ],
    nextStops: [
      25,
      18
    ],
    address: campusAddress("篮球场"),
    tips: "该坐标由手绘地图位置线性估算，具体球场入口需现场复核。",
    source: "手绘地图线性估算",
    coordinateStatus: "estimated",
    estimateAverageErrorMeters: 60,
    estimateMaxErrorMeters: 101,
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 27,
    name: "风雨连廊",
    type: "交通入口",
    description: "根据手绘地图估算的风雨连廊位置，适合连接教学区、生活区和办事区的路径指引。",
    openTime: "全天",
    latitude: 23.2697609,
    longitude: 112.682951,
    mapX: 70,
    mapY: 43,
    image: "",
    featured: false,
    tagline: "校内通行连廊估算点位",
    bestFor: "雨天通行、跨区域找路、集合指引",
    bestTime: "雨天或跨区上课前",
    nearby: [
      "行政中心",
      "J1至善楼",
      "公交站"
    ],
    nextStops: [
      6,
      24
    ],
    address: campusAddress("风雨连廊"),
    tips: "该坐标由手绘地图位置线性估算，连廊入口和覆盖范围需现场复核。",
    source: "手绘地图线性估算",
    coordinateStatus: "estimated",
    estimateAverageErrorMeters: 60,
    estimateMaxErrorMeters: 101,
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 28,
    name: "学生交流中心",
    type: "学习场所",
    description: "高德 POI 标注的校园交流活动点位，可作为学生事务沟通、活动和集合参考点。",
    openTime: "以现场开放为准",
    latitude: 23.270575,
    longitude: 112.678675,
    mapX: 44,
    mapY: 43,
    image: "",
    featured: false,
    tagline: "高德收录的校内交流中心点位",
    bestFor: "活动集合、交流沟通、校内事务指引",
    bestTime: "工作日白天或活动开始前",
    nearby: [
      "综合体育馆",
      "图书馆",
      "S4笃行楼"
    ],
    nextStops: [
      18,
      1
    ],
    address: campusAddress("学生交流中心") + " · 高德地址：520·桌球棋牌·CLUB西北侧280米",
    tips: "该点位来自高德 POI，建议结合现场标识复核名称和入口。",
    source: "高德地图POI",
    amapId: "B0MG9HPFXJ",
    amapType: "科教文化服务;学校;高等院校",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 29,
    name: "学术交流中心",
    type: "学习场所",
    description: "高德 POI 标注的学术交流中心，适合作为讲座、会议和学术活动导航点。",
    openTime: "以现场开放为准",
    latitude: 23.267625,
    longitude: 112.671975,
    mapX: 17,
    mapY: 70,
    image: "",
    featured: false,
    tagline: "高德收录的学术交流点位",
    bestFor: "学术活动、讲座会议、校内交流",
    bestTime: "活动前 15 分钟",
    nearby: [
      "菜鸟驿站",
      "J4治平楼",
      "二期桃蹊饭堂"
    ],
    nextStops: [
      8,
      10
    ],
    address: campusAddress("学术交流中心") + " · 高德地址：莲花镇广州应用科技学院肇庆校区",
    tips: "该点位来自高德 POI，需确认是否与二期片区建筑入口一致。",
    source: "高德地图POI",
    amapId: "B0LDRZ4A8P",
    amapType: "科教文化服务;培训机构;培训机构",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 30,
    name: "二期驿站",
    type: "生活场所",
    description: "高德 POI 标注的二期驿站，可作为二期生活区快递和服务点位参考。",
    openTime: "以现场营业为准",
    latitude: 23.270475,
    longitude: 112.678675,
    mapX: 43,
    mapY: 44,
    image: "",
    featured: false,
    tagline: "高德收录的二期服务驿站",
    bestFor: "快递、物品领取、生活服务咨询",
    bestTime: "下午非高峰时段",
    nearby: [
      "学生交流中心",
      "综合体育馆",
      "S4笃行楼"
    ],
    nextStops: [
      28,
      18
    ],
    address: campusAddress("二期驿站") + " · 高德地址：520·桌球棋牌·CLUB西北侧270米",
    tips: "该点位来自高德 POI，实际服务窗口请以现场为准。",
    source: "高德地图POI",
    amapId: "B0MG273PB9",
    amapType: "科教文化服务;学校;高等院校",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 31,
    name: "内部地面停车场",
    type: "交通入口",
    description: "高德 POI 标注的校内地面停车场，适合作为车辆到校和访客停车指引。",
    openTime: "以现场开放为准",
    latitude: 23.269484,
    longitude: 112.681804,
    mapX: 65,
    mapY: 47,
    image: "",
    featured: false,
    tagline: "校内停车区域点位",
    bestFor: "车辆到校、访客停车、接送定位",
    bestTime: "入校或离校前",
    nearby: [
      "行政中心",
      "公交站",
      "风雨连廊"
    ],
    nextStops: [
      6,
      14
    ],
    address: campusAddress("内部地面停车场") + " · 高德地址：莲花镇丰乐路20号广州应用科技学院(肇庆校区)",
    tips: "停车规则以现场管理为准。",
    source: "高德地图POI",
    amapId: "B0IDDSB7O7",
    amapType: "交通设施服务;停车场;专用停车场",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 32,
    name: "内部地面停车场出入口",
    type: "交通入口",
    description: "高德 POI 标注的停车场出入口，适合作为车辆通行和接送定位点。",
    openTime: "以现场开放为准",
    latitude: 23.269548,
    longitude: 112.682962,
    mapX: 72,
    mapY: 48,
    image: "",
    featured: false,
    tagline: "停车场出入口点位",
    bestFor: "车辆进出、接送集合、访客定位",
    bestTime: "入校和离校时",
    nearby: [
      "公交站",
      "行政中心",
      "风雨连廊"
    ],
    nextStops: [
      14,
      6
    ],
    address: campusAddress("内部地面停车场出入口") + " · 高德地址：广州应用科技学院肇庆校区内部地面停车场",
    tips: "该点位来自高德 POI，车行路线以现场交通组织为准。",
    source: "高德地图POI",
    amapId: "B0IDDSAZGK",
    amapType: "交通设施服务;停车场;停车场出入口",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 33,
    name: "苹果校园体验中心",
    type: "学习场所",
    description: "高德 POI 标注的苹果校园体验中心，可作为数字设备体验和校园服务参考点。",
    openTime: "以现场营业为准",
    latitude: 23.272004,
    longitude: 112.679922,
    mapX: 52,
    mapY: 26,
    image: "",
    featured: false,
    tagline: "校园数字体验服务点",
    bestFor: "设备体验、数字服务咨询、活动集合",
    bestTime: "工作日白天",
    nearby: [
      "图书馆",
      "综合体育馆",
      "篮球场"
    ],
    nextStops: [
      1,
      18
    ],
    address: campusAddress("苹果校园体验中心") + " · 高德地址：广州应用科技学院(肇庆校区)综合体育馆东北侧140米",
    tips: "该点位来自高德 POI，服务内容以现场为准。",
    source: "高德地图POI",
    amapId: "B0L1HCXE5J",
    amapType: "科教文化服务;学校;高等院校",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 34,
    name: "莲花大剧院",
    type: "学习场所",
    description: "高德 POI 标注的剧院点位，可作为演出、讲座和大型活动的导航参考。",
    openTime: "以活动安排为准",
    latitude: 23.267832,
    longitude: 112.674789,
    mapX: 28,
    mapY: 66,
    image: "/images/campus/lianhua-theater.jpg",
    featured: false,
    tagline: "活动与演出场地",
    bestFor: "讲座、演出、学院活动和集合",
    bestTime: "活动开始前",
    nearby: [
      "J3修齐楼",
      "S5致用楼",
      "桃蹊餐厅"
    ],
    nextStops: [
      9,
      11
    ],
    address: campusAddress("莲花大剧院") + " · 高德地址：广州应用科技学院(肇庆校区)集贤苑C栋附近",
    tips: "该点位来自高德 POI，具体入口和活动安排请以现场通知为准。",
    source: "高德地图POI",
    amapId: "B0LUOSI8FV",
    amapType: "科教文化服务;学校;学校",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 35,
    name: "音乐学院",
    type: "学习场所",
    description: "高德 POI 标注的音乐学院点位，位于治平楼相关区域。",
    openTime: "以学院安排为准",
    latitude: 23.266478,
    longitude: 112.673144,
    mapX: 22,
    mapY: 74,
    image: "",
    featured: false,
    tagline: "音乐学院教学与活动点位",
    bestFor: "音乐学院课程、排练、活动导航",
    bestTime: "上课或活动前",
    nearby: [
      "音乐厅",
      "J4治平楼",
      "J3修齐楼"
    ],
    nextStops: [
      36,
      10
    ],
    address: campusAddress("音乐学院") + " · 高德地址：治平楼负一层",
    tips: "该点位来自高德 POI，楼层信息需现场复核。",
    source: "高德地图POI",
    amapId: "B0MALG5WJF",
    amapType: "科教文化服务;学校;高等院校",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 36,
    name: "音乐厅",
    type: "学习场所",
    description: "高德 POI 标注的音乐厅点位，适合作为演出、排练和课程活动导航点。",
    openTime: "以活动安排为准",
    latitude: 23.266504,
    longitude: 112.67322,
    mapX: 23,
    mapY: 74,
    image: "",
    featured: false,
    tagline: "音乐活动与演出点位",
    bestFor: "音乐演出、排练、课程活动",
    bestTime: "活动开始前",
    nearby: [
      "音乐学院",
      "J4治平楼",
      "J3修齐楼"
    ],
    nextStops: [
      35,
      10
    ],
    address: campusAddress("音乐厅") + " · 高德地址：广州应用科技学院治平楼一楼",
    tips: "该点位来自高德 POI，具体入口和楼层请以现场为准。",
    source: "高德地图POI",
    amapId: "B0L0Z7F71U",
    amapType: "科教文化服务;学校;高等院校",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  },
  {
    id: 37,
    name: "桃蹊餐厅",
    type: "生活场所",
    description: "高德 POI 标注的桃蹊餐厅点位，适合作为二期生活区餐饮导航参考。",
    openTime: "以现场营业为准",
    latitude: 23.268425,
    longitude: 112.674975,
    mapX: 32,
    mapY: 62,
    image: "",
    featured: false,
    tagline: "二期餐饮服务点位",
    bestFor: "就餐、补给、活动前后集合",
    bestTime: "饭点前后错峰",
    nearby: [
      "莲花大剧院",
      "S5致用楼",
      "J3修齐楼"
    ],
    nextStops: [
      34,
      11
    ],
    address: campusAddress("桃蹊餐厅") + " · 高德地址：莲花大剧院北侧60米",
    tips: "该点位来自高德 POI，营业窗口和开放时间以现场为准。",
    source: "高德地图POI",
    amapId: "B0LKXCOZ0O",
    amapType: "餐饮服务;中餐厅;中餐厅",
    coordinateStatus: "amap",
    reviewRequired: true,
    coordinateSystem: "GCJ-02"
  }
];

