module.exports = [
  {
    id: 1,
    title: '图书借阅与电子资源',
    type: '学习服务',
    category: '学习资源',
    group: '学习资源',
    tag: '常用',
    featured: true,
    freshmanPriority: true,
    priority: 2,
    placeIds: [1],
    location: '图书馆一层总服务台',
    time: '08:00-22:00',
    content: '提供图书借阅、馆藏查询、阅览室咨询与电子资源使用指导。',
    materials: ['校园卡或学生证', '图书馆账号'],
    steps: ['到总服务台确认账号状态', '按需咨询借阅、数据库或自习空间', '保存常用入口方便下次查看'],
    actionText: '去图书馆办理',
    phone: '0758-000001'
  },
  {
    id: 2,
    title: '校园卡与餐饮咨询',
    type: '生活服务',
    category: '宿舍后勤',
    group: '宿舍后勤',
    tag: '高频',
    featured: true,
    freshmanPriority: true,
    priority: 1,
    placeIds: [3],
    location: '一期桃园饭堂服务窗口',
    time: '07:00-20:00',
    content: '处理校园卡充值咨询、餐饮窗口信息、错峰用餐建议和支付异常反馈。',
    materials: ['校园卡', '学生证或学号', '支付记录截图'],
    steps: ['先确认校园卡余额或支付记录', '到食堂服务窗口说明问题', '保留处理结果，必要时联系后勤服务'],
    actionText: '去食堂服务窗口',
    phone: '0758-000002'
  },
  {
    id: 3,
    title: '教室与学习空间咨询',
    type: '学习服务',
    category: '教学保障',
    group: '教学保障',
    tag: '办事',
    featured: false,
    freshmanPriority: true,
    priority: 5,
    placeIds: [2],
    location: '格致楼值班室',
    time: '09:00-17:30',
    content: '受理自习空间、班级活动、临时教室和教学楼路线咨询。',
    materials: ['学生证', '使用时间说明', '班级或组织信息'],
    steps: ['确认需要使用的时间段', '到教学楼值班室咨询可用空间', '按值班老师要求登记信息'],
    actionText: '咨询教学楼值班室',
    phone: '0758-000003'
  },
  {
    id: 4,
    title: '社团活动与志愿报名',
    type: '活动服务',
    category: '校园活动',
    group: '校园活动',
    tag: '推荐',
    featured: true,
    freshmanPriority: true,
    priority: 4,
    placeIds: [14],
    location: '广州应用科技学院公交站旁校园服务咨询点',
    time: '10:00-18:00',
    content: '发布社团活动、志愿服务、校园开放日和创新竞赛报名信息。',
    materials: ['学生证', '个人联系方式', '意向社团或活动名称'],
    steps: ['查看近期活动海报', '到活动中心服务台咨询报名方式', '按活动要求加入通知群或提交报名'],
    actionText: '查看活动报名',
    phone: '0758-000004'
  },
  {
    id: 5,
    title: '校园网与设备报修',
    type: '学习服务',
    category: '网络报修',
    group: '网络报修',
    tag: '技术',
    featured: true,
    freshmanPriority: true,
    priority: 3,
    placeIds: [2, 11],
    location: '格致楼 / S5致用楼教学支持点',
    time: '08:30-20:00',
    content: '提供校园网连接咨询、机房开放信息、账号异常和基础设备报修指引。',
    materials: ['学号', '设备型号', '故障截图或错误提示'],
    steps: ['先记录网络或设备异常现象', '到格致楼或 S5 致用楼教学支持点说明问题', '按工作人员指引完成登记或复测'],
    actionText: '发起网络咨询',
    phone: '0758-000005'
  },
  {
    id: 6,
    title: '快递打印与生活补给',
    type: '生活服务',
    category: '宿舍后勤',
    group: '宿舍后勤',
    tag: '高频',
    featured: true,
    freshmanPriority: true,
    priority: 6,
    placeIds: [8, 12],
    location: '菜鸟驿站 / 二期桃蹊饭堂附近',
    time: '09:00-20:30',
    content: '提供快递收发、自助打印、复印和常见生活辅助服务。',
    materials: ['取件码', '身份证明', '待打印文件'],
    steps: ['准备取件码或打印文件', '到快递服务点按窗口指引办理', '高峰期建议错峰前往'],
    actionText: '去快递服务点',
    phone: '0758-000006'
  },
  {
    id: 7,
    title: '学生办事与证明咨询',
    type: '办事服务',
    category: '学籍事务',
    group: '学籍事务',
    tag: '学生',
    featured: true,
    freshmanPriority: true,
    priority: 0,
    placeIds: [6],
    location: '行政中心',
    time: '08:30-17:30',
    content: '适合处理学籍、证明、校园卡、入学材料和常见校园事务咨询。',
    materials: ['学生证或录取信息', '身份证', '相关申请材料'],
    steps: ['先确认要办理的事项', '准备身份证明和申请材料', '到行政中心取号或咨询窗口'],
    actionText: '查看行政中心',
    phone: '0758-000007'
  },
  {
    id: 8,
    title: '综合体育馆开放与活动提醒',
    type: '活动服务',
    category: '校园活动',
    group: '校园活动',
    tag: '夜间',
    featured: false,
    freshmanPriority: false,
    priority: 8,
    placeIds: [18],
    location: '综合体育馆',
    time: '18:00-22:00',
    content: '提供体育馆活动、班级球赛、公共场地使用和运动安全注意事项。',
    materials: ['运动装备', '饮用水', '班级活动说明'],
    steps: ['确认开放时段和活动安排', '到综合体育馆按区域活动', '夜间运动注意结伴和安全'],
    actionText: '查看综合体育馆',
    phone: '0758-000008'
  },
  {
    id: 9,
    title: '失物招领与紧急联系',
    type: '生活服务',
    category: '安全应急',
    group: '安全应急',
    tag: '应急',
    featured: true,
    freshmanPriority: true,
    priority: 7,
    placeIds: [6, 14],
    location: '行政中心 / 广州应用科技学院公交站',
    time: '08:30-21:00',
    content: '处理失物登记、拾物归还、紧急联系人查询和校园安全提醒。',
    materials: ['学生证', '物品照片或特征说明', '联系方式'],
    steps: ['记录物品遗失时间和地点', '到服务台登记或查询', '留下联系方式等待后续反馈'],
    actionText: '登记失物信息',
    phone: '0758-000009'
  }
];

