module.exports = [
  {
    id: 1,
    title: 'WXML 基础',
    category: '页面结构',
    stage: 'entry',
    stageLabel: '入门',
    duration: '8 min',
    keywords: ['WXML', '组件', '结构'],
    relatedIds: [2, 3],
    featured: true,
    summary: '了解 view、text、image、block 等基础结构组件。',
    content: 'WXML 是微信小程序的页面结构语言，负责描述界面层级、数据绑定和条件渲染。实际开发中常用 view 进行布局，text 展示文本，block 包裹 wx:if 与 wx:for。',
    code: '<view class="card">\n  <text>{{title}}</text>\n</view>'
  },
  {
    id: 2,
    title: 'WXSS 样式组织',
    category: '样式设计',
    stage: 'entry',
    stageLabel: '入门',
    duration: '10 min',
    keywords: ['WXSS', 'rpx', '样式复用'],
    relatedIds: [1, 4],
    featured: true,
    summary: '学习 rpx、自定义类名和页面样式拆分。',
    content: 'WXSS 在 CSS 的基础上提供了 rpx 响应式单位，适合在不同尺寸手机上做比例适配。项目开发中建议统一卡片、按钮、标签等样式类，提高页面一致性。',
    code: '.card {\n  padding: 24rpx;\n  border-radius: 20rpx;\n  background: #ffffff;\n}'
  },
  {
    id: 3,
    title: 'Page 生命周期',
    category: '逻辑交互',
    stage: 'common',
    stageLabel: '常用',
    duration: '9 min',
    keywords: ['Page', '生命周期', 'onShow'],
    relatedIds: [1, 5],
    featured: false,
    summary: '掌握 onLoad、onShow、onUnload 的典型使用场景。',
    content: '详情页通常在 onLoad 中根据 id 拉取数据，tabBar 页面在 onShow 中刷新登录状态和收藏数量，这也是本项目收藏同步与个人中心刷新的基础。',
    code: 'Page({\n  onLoad(options) {\n    this.loadDetail(options.id);\n  },\n  onShow() {\n    this.syncStatus();\n  }\n});'
  },
  {
    id: 4,
    title: '常用小程序 API',
    category: '小程序API',
    stage: 'common',
    stageLabel: '常用',
    duration: '12 min',
    keywords: ['API', 'navigateTo', 'storage'],
    relatedIds: [2, 3],
    featured: true,
    summary: '使用 navigateTo、setStorageSync、showToast 等完成交互。',
    content: '小程序 API 是用户体验的重要支撑。本项目会用到页面跳转、本地缓存、地图打开、剪贴板复制和消息提示等能力。',
    code: "wx.showToast({ title: '保存成功', icon: 'success' });"
  },
  {
    id: 5,
    title: '单例与观察者模式',
    category: '设计模式',
    stage: 'advanced',
    stageLabel: '进阶',
    duration: '14 min',
    keywords: ['单例', '观察者', '状态同步'],
    relatedIds: [3, 4],
    featured: true,
    summary: '把抽象概念落实到用户状态与收藏同步中。',
    content: 'UserManager 以单例方式统一管理登录用户；FavoriteSubject 以观察者模式广播收藏变化，解决 tabBar 页与详情页状态不同步的问题。',
    code: "favoriteSubject.subscribe('user-page', () => {\n  this.refreshFavoriteCount();\n});"
  },
  {
    id: 6,
    title: '条件渲染与列表渲染',
    category: '页面结构',
    stage: 'entry',
    stageLabel: '入门',
    duration: '9 min',
    keywords: ['wx:if', 'wx:for', '列表'],
    relatedIds: [1, 2],
    featured: false,
    summary: '理解列表和条件在小程序页面中的基本写法。',
    content: '小程序页面中常见的组织方式是把数据列表通过 wx:for 输出，再用 wx:if 处理空状态、加载态和登录态。',
    code: '<view wx:if="{{list.length}}">\n  <view wx:for="{{list}}" wx:key="id">{{item.title}}</view>\n</view>'
  },
  {
    id: 7,
    title: '页面数据绑定与 setData',
    category: '逻辑交互',
    stage: 'common',
    stageLabel: '常用',
    duration: '11 min',
    keywords: ['setData', '数据绑定', '状态'],
    relatedIds: [3, 4],
    featured: true,
    summary: '掌握页面状态更新和视图同步的关键方式。',
    content: '页面中的筛选、搜索、收藏数刷新，本质都依赖 setData 把最新状态同步到视图层，这也是小程序交互的核心基础。',
    code: "this.setData({\n  keyword: event.detail.value,\n  loading: false\n});"
  },
  {
    id: 8,
    title: '本地缓存与多账号隔离',
    category: '小程序API',
    stage: 'common',
    stageLabel: '常用',
    duration: '13 min',
    keywords: ['storage', '缓存', '账号隔离'],
    relatedIds: [4, 5],
    featured: false,
    summary: '用本地缓存实现收藏、学习记录和用户隔离。',
    content: '这个项目的收藏和学习记录按 studentId 分桶保存，既能保留个人数据，又避免多个测试账号互相污染，是更接近真实产品的实现方式。',
    code: "wx.setStorageSync('campus-guide:favorites', nextStore);"
  },
  {
    id: 9,
    title: '模块拆分与服务层组织',
    category: '设计模式',
    stage: 'advanced',
    stageLabel: '进阶',
    duration: '15 min',
    keywords: ['service', '拆分', '职责'],
    relatedIds: [5, 8],
    featured: true,
    summary: '把 request facade 和内部 service 拆分成更清晰的职责边界。',
    content: '随着页面功能变多，直接把所有 mock 接口都堆在一个文件里会很难维护，所以把 home、notice、study、favorite 等 service 分开是更成熟的结构。',
    code: "const homeService = require('./services/homeService');\nconst studyService = require('./services/studyService');"
  },
  {
    id: 10,
    title: '推荐逻辑与派生状态',
    category: '设计模式',
    stage: 'advanced',
    stageLabel: '进阶',
    duration: '16 min',
    keywords: ['selector', '推荐', '派生状态'],
    relatedIds: [5, 9],
    featured: true,
    summary: '理解如何从原始数据中派生出推荐地点、学习进度和下一步建议。',
    content: '推荐卡片、学习进度和下一条学习建议都不是手写死的，而是从原始地点、学习、历史和收藏数据中派生出来的，这能显著提高页面真实感。',
    code: "const studySummary = selectors.getStudyProgressSummary(studyData, history, favoriteList);"
  }
];
